import type { CountryTaxInfo, TaxRegime } from './types';

export const REGIME_COLORS: Record<TaxRegime, string> = {
  exemption: '#10B981',
  flat_tax: '#F59E0B',
  capital_gains: '#8B5CF6',
  progressive: '#EF4444',
  unclear: '#64748B',
};

export const REGIME_LABELS: Record<TaxRegime, string> = {
  exemption: 'Exemption (0%)',
  flat_tax: 'Flat tax',
  capital_gains: 'Plus-values',
  progressive: 'Progressif',
  unclear: 'Cadre flou',
};

export const FLAG_EMOJI: Record<string, string> = {
  FR: '\u{1F1EB}\u{1F1F7}', DE: '\u{1F1E9}\u{1F1EA}', BE: '\u{1F1E7}\u{1F1EA}',
  CH: '\u{1F1E8}\u{1F1ED}', PT: '\u{1F1F5}\u{1F1F9}', ES: '\u{1F1EA}\u{1F1F8}',
  IT: '\u{1F1EE}\u{1F1F9}', NL: '\u{1F1F3}\u{1F1F1}', GB: '\u{1F1EC}\u{1F1E7}',
  IE: '\u{1F1EE}\u{1F1EA}', AT: '\u{1F1E6}\u{1F1F9}', SE: '\u{1F1F8}\u{1F1EA}',
  NO: '\u{1F1F3}\u{1F1F4}', DK: '\u{1F1E9}\u{1F1F0}', FI: '\u{1F1EB}\u{1F1EE}',
  PL: '\u{1F1F5}\u{1F1F1}', CZ: '\u{1F1E8}\u{1F1FF}', MT: '\u{1F1F2}\u{1F1F9}',
  EE: '\u{1F1EA}\u{1F1EA}', LU: '\u{1F1F1}\u{1F1FA}',
  AE: '\u{1F1E6}\u{1F1EA}', SG: '\u{1F1F8}\u{1F1EC}', HK: '\u{1F1ED}\u{1F1F0}',
  SV: '\u{1F1F8}\u{1F1FB}', PA: '\u{1F1F5}\u{1F1E6}', BS: '\u{1F1E7}\u{1F1F8}',
  BM: '\u{1F1E7}\u{1F1F2}', GE: '\u{1F1EC}\u{1F1EA}', MY: '\u{1F1F2}\u{1F1FE}',
  PY: '\u{1F1F5}\u{1F1FE}',
  US: '\u{1F1FA}\u{1F1F8}', CA: '\u{1F1E8}\u{1F1E6}', BR: '\u{1F1E7}\u{1F1F7}',
  AR: '\u{1F1E6}\u{1F1F7}', MX: '\u{1F1F2}\u{1F1FD}', CO: '\u{1F1E8}\u{1F1F4}',
  JP: '\u{1F1EF}\u{1F1F5}', KR: '\u{1F1F0}\u{1F1F7}', AU: '\u{1F1E6}\u{1F1FA}',
  NZ: '\u{1F1F3}\u{1F1FF}', IN: '\u{1F1EE}\u{1F1F3}', TH: '\u{1F1F9}\u{1F1ED}',
  ID: '\u{1F1EE}\u{1F1E9}', PH: '\u{1F1F5}\u{1F1ED}',
  IL: '\u{1F1EE}\u{1F1F1}', ZA: '\u{1F1FF}\u{1F1E6}', NG: '\u{1F1F3}\u{1F1EC}',
  MA: '\u{1F1F2}\u{1F1E6}',
};

// Map ISO alpha-2 to ISO 3166-1 numeric (used by topojson)
export const ALPHA2_TO_NUMERIC: Record<string, string> = {
  FR: '250', DE: '276', BE: '056', CH: '756', PT: '620', ES: '724',
  IT: '380', NL: '528', GB: '826', IE: '372', AT: '040', SE: '752',
  NO: '578', DK: '208', FI: '246', PL: '616', CZ: '203', MT: '470',
  EE: '233', LU: '442',
  AE: '784', SG: '702', HK: '344', SV: '222', PA: '591', BS: '044',
  BM: '060', GE: '268', MY: '458', PY: '600',
  US: '840', CA: '124', BR: '076', AR: '032', MX: '484', CO: '170',
  JP: '392', KR: '410', AU: '036', NZ: '554', IN: '356', TH: '764',
  ID: '360', PH: '608',
  IL: '376', ZA: '710', NG: '566', MA: '504',
};

// Reverse mapping: numeric -> alpha-2
export const NUMERIC_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(ALPHA2_TO_NUMERIC).map(([a2, num]) => [num, a2])
);

export const TAX_DATA: CountryTaxInfo[] = [
  // ─── EUROPE ────────────────────────────────────────
  {
    code: 'FR', numericCode: '250', name: 'France',
    regime: 'flat_tax', rates: '30%', rateValue: 30,
    holdingPeriodRules: [],
    exemptions: ['Cessions < 305 euros/an exonerees', 'Echanges crypto-crypto non imposables'],
    keyRules: ['PFU 30% (12,8% IR + 17,2% PS) en 2025', 'PFU 31,4% en 2026 (hausse PS)', 'Option bareme progressif possible', 'Methode PMPA obligatoire'],
    notes: 'Le PFU est simple mais le bareme progressif peut etre avantageux pour les petits revenus. Declaration via formulaire 2086.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Article 150 VH bis CGI', url: 'https://www.legifrance.gouv.fr/' }],
  },
  {
    code: 'DE', numericCode: '276', name: 'Allemagne',
    regime: 'progressive', rates: '0-45%', rateValue: 25,
    holdingPeriodRules: [{ period: '> 1 an', benefit: 'Exoneration totale des plus-values' }],
    exemptions: ['Plus-values < 600 euros/an exonerees', 'Exoneration apres 1 an de detention'],
    keyRules: ['Barème progressif IR (0-45%) si vente < 1 an', 'Detention > 1 an = 0% d\'impot', 'Seuil de 600 euros/an (Freigrenze)'],
    notes: 'Un des regimes les plus favorables en Europe pour les holders long terme. Le seuil de 600 euros est un "Freigrenze" : si depasse, tout est impose.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'BZSt', url: 'https://www.bzst.de/' }],
  },
  {
    code: 'BE', numericCode: '056', name: 'Belgique',
    regime: 'capital_gains', rates: '33%', rateValue: 33,
    holdingPeriodRules: [],
    exemptions: ['Gestion "normale" du patrimoine prive = 0%'],
    keyRules: ['Particulier en "bon pere de famille" = 0%', 'Speculation ou activite pro = 33% + taxe communale', 'Ligne floue entre gestion normale et speculation'],
    notes: 'La Belgique ne taxe pas les gains en capital "normaux" mais la frontiere avec la speculation est floue. Le fisc peut requalifier en revenus divers (33%) ou professionnels (bareme IR).',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SPF Finances', url: 'https://finances.belgium.be/' }],
  },
  {
    code: 'CH', numericCode: '756', name: 'Suisse',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Gains en capital prives non imposes', 'Impot sur la fortune cantonal sur le solde crypto'],
    keyRules: ['0% sur les plus-values pour particuliers', 'Trading pro = activite independante (imposable)', 'Impot sur la fortune variable par canton', 'Valeur declaree au 31 decembre'],
    notes: 'Paradis fiscal pour les holders. L\'impot sur la fortune cantonal (0,1% a 1% selon le canton) s\'applique sur la valeur du portefeuille. Zoug est la "Crypto Valley".',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'AFC Suisse', url: 'https://www.estv.admin.ch/' }],
  },
  {
    code: 'PT', numericCode: '620', name: 'Portugal',
    regime: 'capital_gains', rates: '28%', rateValue: 28,
    holdingPeriodRules: [{ period: '> 365 jours', benefit: 'Exoneration totale' }],
    exemptions: ['Detention > 365 jours = exoneration', 'Gains < 500 euros exclus'],
    keyRules: ['28% sur plus-values si detention < 365 jours', 'Exoneration totale apres 1 an', 'Regime NHR supprime fin 2023 (remplace par IFICI)'],
    notes: 'Depuis janvier 2023, les crypto sont imposees au Portugal. L\'exoneration apres 1 an reste très attractive pour les investisseurs long terme.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Autoridade Tributaria', url: 'https://www.portaldasfinancas.gov.pt/' }],
  },
  {
    code: 'ES', numericCode: '724', name: 'Espagne',
    regime: 'progressive', rates: '19-28%', rateValue: 23,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['Bareme progressif : 19% (< 6k), 21% (6-50k), 23% (50-200k), 27% (200-300k), 28% (> 300k)', 'Declaration obligatoire via Modelo 721 si > 50k euros a l\'etranger', 'Modelo 100 pour la declaration annuelle'],
    notes: 'L\'Espagne a un systeme progressif avec des tranches. Le Modelo 721 remplace le Modelo 720 pour les actifs crypto a l\'etranger depuis 2024.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Agencia Tributaria', url: 'https://sede.agenciatributaria.gob.es/' }],
  },
  {
    code: 'IT', numericCode: '380', name: 'Italie',
    regime: 'flat_tax', rates: '26%', rateValue: 26,
    holdingPeriodRules: [],
    exemptions: ['Seuil de 2 000 euros de plus-value (franchise)'],
    keyRules: ['Imposta sostitutiva de 26% sur les plus-values', 'Seuil de franchise de 2 000 euros/an', 'Declaration via quadro RW et RT', 'Regime fiscal clarifie depuis 2023'],
    notes: 'L\'Italie a clarifie la fiscalite crypto en 2023 avec un taux fixe de 26%. Un amnistie fiscale a ete proposee pour les annees precedentes. Le seuil de franchise peut evoluer.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Agenzia delle Entrate', url: 'https://www.agenziaentrate.gov.it/' }],
  },
  {
    code: 'NL', numericCode: '528', name: 'Pays-Bas',
    regime: 'capital_gains', rates: '~1,2-1,6%', rateValue: 36,
    holdingPeriodRules: [],
    exemptions: ['Seuil d\'exoneration (heffingsvrij vermogen) ~57 000 euros'],
    keyRules: ['Regime Box 3 : impot sur rendement fictif (pas sur gains reels)', 'Taux effectif ~ 1,2% a 1,6% de la valeur du patrimoine', 'Reforme en cours vers imposition des gains reels', 'Seuil : ~57 000 euros (2025) par personne'],
    notes: 'Le systeme neerlandais Box 3 taxe un rendement presume sur le patrimoine, pas les gains reels. Taux composite autour de 36% sur le rendement fictif, soit ~1,2-1,6% de la valeur totale. Reforme prevue.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Belastingdienst', url: 'https://www.belastingdienst.nl/' }],
  },
  {
    code: 'GB', numericCode: '826', name: 'Royaume-Uni',
    regime: 'capital_gains', rates: '10-20%', rateValue: 15,
    holdingPeriodRules: [],
    exemptions: ['Annual Exempt Amount : 3 000 GBP (2024/25)'],
    keyRules: ['CGT : 10% (basic rate) ou 20% (higher rate)', 'Annual Exempt Amount 3 000 GBP', 'HMRC traite les crypto comme des biens', 'Staking/mining = income tax potentiel'],
    notes: 'Le Royaume-Uni a un regime clair avec le CGT standard. L\'allocation annuelle a ete reduite a 3 000 GBP depuis 2024/25 (etait 12 300 GBP avant).',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'HMRC Crypto', url: 'https://www.gov.uk/government/publications/tax-on-cryptoassets' }],
  },
  {
    code: 'IE', numericCode: '372', name: 'Irlande',
    regime: 'capital_gains', rates: '33%', rateValue: 33,
    holdingPeriodRules: [],
    exemptions: ['Abattement annuel de 1 270 euros'],
    keyRules: ['CGT de 33% sur les plus-values crypto', 'Abattement de 1 270 euros/an', 'Declaration Self-Assessment obligatoire', 'Income tax possible sur staking/mining'],
    notes: 'Taux CGT parmi les plus eleves d\'Europe. L\'Irlande compense par un environnement favorable aux entreprises crypto.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Revenue.ie', url: 'https://www.revenue.ie/' }],
  },
  {
    code: 'AT', numericCode: '040', name: 'Autriche',
    regime: 'flat_tax', rates: '27,5%', rateValue: 27.5,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['KESt de 27,5% (comme les actions)', 'Regime clarifie depuis mars 2022', 'Echanges crypto-crypto imposables (contrairement a la France)', 'Staking/lending = revenus du capital (27,5%)'],
    notes: 'Depuis 2022, l\'Autriche aligne les crypto sur les actifs financiers classiques. Les echanges crypto-crypto sont imposables, ce qui differe de la France.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'BMF Osterreich', url: 'https://www.bmf.gv.at/' }],
  },
  {
    code: 'SE', numericCode: '752', name: 'Suede',
    regime: 'flat_tax', rates: '30%', rateValue: 30,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['30% sur les gains en capital', 'Aucune exoneration liee a la duree de detention', 'Pertes deductibles a 70%', 'Declaration via Skatteverket (K4)'],
    notes: 'La Suede applique un taux fixe de 30% sans exoneration. Les pertes sont deductibles a 70% des gains. Regime simple mais sans avantage pour les holders.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Skatteverket', url: 'https://www.skatteverket.se/' }],
  },
  {
    code: 'NO', numericCode: '578', name: 'Norvege',
    regime: 'flat_tax', rates: '22%', rateValue: 22,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['22% sur les gains en capital', 'Regime standard d\'imposition des actifs', 'Impot sur la fortune si patrimoine > seuil'],
    notes: 'La Norvege applique le taux standard de 22% sur les gains en capital. Un impot sur la fortune s\'ajoute pour les patrimoines importants.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Skatteetaten', url: 'https://www.skatteetaten.no/' }],
  },
  {
    code: 'DK', numericCode: '208', name: 'Danemark',
    regime: 'progressive', rates: '37-52%', rateValue: 42,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['Revenu du capital personnel (37-52%)', 'Pas de regime specifique aux crypto', 'Pertes deductibles sous conditions', 'Projet de loi pour inventaire au 1er janv 2026'],
    notes: 'Le Danemark a l\'une des fiscalites les plus lourdes d\'Europe pour les crypto. Les gains sont traites comme du revenu du capital personnel, avec des taux pouvant depasser 50%.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Skattestyrelsen', url: 'https://skat.dk/' }],
  },
  {
    code: 'FI', numericCode: '246', name: 'Finlande',
    regime: 'capital_gains', rates: '30-34%', rateValue: 30,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['30% sur les premiers 30 000 euros de gains', '34% au-dela de 30 000 euros', 'Echanges crypto-crypto imposables'],
    notes: 'La Finlande impose un systeme a deux paliers sur les gains en capital. Les echanges crypto-crypto declenchent aussi l\'impot.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Vero.fi', url: 'https://www.vero.fi/' }],
  },
  {
    code: 'PL', numericCode: '616', name: 'Pologne',
    regime: 'flat_tax', rates: '19%', rateValue: 19,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['19% flat tax sur les plus-values', 'Echanges crypto-crypto non imposables', 'Pertes reportables sur 5 ans'],
    notes: 'La Pologne offre un taux fixe competitif de 19%. Les echanges crypto-crypto ne sont pas un fait generateur, comme en France.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'KIS', url: 'https://www.kis.gov.pl/' }],
  },
  {
    code: 'CZ', numericCode: '203', name: 'Republique tcheque',
    regime: 'flat_tax', rates: '15%', rateValue: 15,
    holdingPeriodRules: [{ period: '> 3 ans', benefit: 'Exoneration totale (depuis 2025)' }],
    exemptions: ['Gains < 100 000 CZK/an (~4 000 EUR) exoneres si detention > 3 ans'],
    keyRules: ['15% flat tax (ou 23% au-dela de ~1,9M CZK)', 'Exoneration si detention > 3 ans et gains < 100 000 CZK', 'Regime clarifie depuis 2024-2025'],
    notes: 'La Republique tcheque a recemment clarifie sa position avec un regime favorable pour les detenteurs long terme.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Financni sprava', url: 'https://www.financnisprava.cz/' }],
  },
  {
    code: 'MT', numericCode: '470', name: 'Malte',
    regime: 'progressive', rates: '0-35%', rateValue: 15,
    holdingPeriodRules: [],
    exemptions: ['Tokens long terme (> 12 mois) = taux reduit'],
    keyRules: ['Bareme progressif IR (0-35%)', 'Distinction tokens financiers / utilitaires', 'Framework MFSA detaille', 'Taux effectif souvent reduit via structures'],
    notes: 'Malte a ete pionniere dans la regulation crypto (framework MFSA 2018). Le taux effectif depend du type de token et de la structure.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'MFSA', url: 'https://www.mfsa.mt/' }],
  },
  {
    code: 'EE', numericCode: '233', name: 'Estonie',
    regime: 'flat_tax', rates: '20%', rateValue: 20,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['20% sur les gains en capital (income tax)', 'Regime e-residency ne change pas la fiscalite perso', 'Declaration comme revenus'],
    notes: 'Malgre son image tech-friendly et le programme e-Residency, la fiscalite crypto estonienne reste standard a 20%.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'EMTA', url: 'https://www.emta.ee/' }],
  },
  {
    code: 'LU', numericCode: '442', name: 'Luxembourg',
    regime: 'capital_gains', rates: '0-42%', rateValue: 21,
    holdingPeriodRules: [{ period: '> 6 mois', benefit: 'Exoneration totale (speculation)' }],
    exemptions: ['Plus-values non speculatives (> 6 mois) = 0%', 'Abattement de 50 000 euros sur plus-values speculatives'],
    keyRules: ['Detention > 6 mois = exoneration totale', 'Speculation (< 6 mois) = bareme IR (0-42%)', 'Abattement 50 000 EUR (100 000 couple)'],
    notes: 'Le Luxembourg offre un des meilleurs regimes europeens grace a l\'exoneration apres 6 mois seulement. L\'abattement genereux protege les petits gains a court terme.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'ACD Luxembourg', url: 'https://impotsdirects.public.lu/' }],
  },

  // ─── CRYPTO-FRIENDLY ──────────────────────────────
  {
    code: 'AE', numericCode: '784', name: 'Emirats arabes unis',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Aucun impot sur le revenu des particuliers', 'Aucun impot sur les gains en capital'],
    keyRules: ['0% impot sur le revenu', '0% impot sur les gains en capital', 'Zones franches pour entreprises crypto (VARA Dubai)', 'Impot sur les societes 9% (depuis 2023) mais exclut les gains en capital perso'],
    notes: 'Dubai et Abu Dhabi sont des hubs crypto majeurs. Le cadre regulatoire VARA (Dubai) est l\'un des plus avances. Aucun impot pour les particuliers.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'VARA Dubai', url: 'https://www.vara.ae/' }],
  },
  {
    code: 'SG', numericCode: '702', name: 'Singapour',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Pas d\'impot sur les gains en capital'],
    keyRules: ['0% gains en capital pour particuliers', 'Trading frequent peut etre requalifie en revenu (0-22%)', 'Licence MAS obligatoire pour les entreprises', 'GST (TVA) ne s\'applique pas aux tokens de paiement depuis 2020'],
    notes: 'Singapour ne taxe pas les gains en capital mais le trading professionnel peut etre soumis a l\'impot sur le revenu. Le cadre MAS est strict pour les entreprises.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'IRAS', url: 'https://www.iras.gov.sg/' }],
  },
  {
    code: 'HK', numericCode: '344', name: 'Hong Kong',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Aucun impot sur les gains en capital'],
    keyRules: ['0% sur les gains en capital', 'Trading professionnel = profits tax (16,5%)', 'Regime de licences VASP depuis juin 2023', 'Hub crypto asiatique majeur'],
    notes: 'Hong Kong ne taxe pas les gains en capital. Le nouveau regime de licences VASP clarifie le cadre pour les plateformes.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SFC Hong Kong', url: 'https://www.sfc.hk/' }],
  },
  {
    code: 'SV', numericCode: '222', name: 'El Salvador',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Bitcoin a cours legal depuis 2021', 'Aucun impot sur les gains Bitcoin pour les etrangers'],
    keyRules: ['Bitcoin = monnaie legale (Ley Bitcoin 2021)', '0% impot sur gains en capital Bitcoin (investisseurs etrangers)', 'Programme de residences Bitcoin', 'Obligations de reporting pour les entreprises'],
    notes: 'Premier pays au monde a adopter le Bitcoin comme monnaie legale. Les investisseurs etrangers beneficient d\'une exoneration totale.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Ley Bitcoin', url: 'https://www.bcr.gob.sv/' }],
  },
  {
    code: 'PA', numericCode: '591', name: 'Panama',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Systeme territorial : revenus etrangers non imposables'],
    keyRules: ['Systeme fiscal territorial', 'Gains crypto d\'origine etrangere = 0%', 'Gains locaux potentiellement imposables', 'Cadre regulatoire encore en developpement'],
    notes: 'Le regime territorial panamaen exonere les revenus d\'origine etrangere. La plupart des gains crypto echappent a l\'impot si les exchanges sont a l\'etranger.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'DGI Panama', url: 'https://dgi.mef.gob.pa/' }],
  },
  {
    code: 'BS', numericCode: '044', name: 'Bahamas',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Aucun impot sur le revenu ou les gains en capital'],
    keyRules: ['0% impot sur le revenu', '0% impot sur les gains en capital', 'Framework DARE Act pour les actifs numeriques', 'Registre d\'exchanges obligatoire'],
    notes: 'Les Bahamas ont adopte le DARE Act en 2020 pour reguler les actifs numeriques tout en maintenant un regime fiscal nul pour les particuliers.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SCB Bahamas', url: 'https://www.scb.gov.bs/' }],
  },
  {
    code: 'GE', numericCode: '268', name: 'Georgie',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Gains en capital des particuliers non imposes'],
    keyRules: ['0% gains en capital pour les residents', 'Regime fiscal territorial favorable', 'Activite pro/entreprise = 20% impot sur les societes'],
    notes: 'La Georgie attire les digital nomads avec un regime fiscal genereux. Les gains en capital des particuliers ne sont pas imposes.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Revenue Service Georgia', url: 'https://rs.ge/' }],
  },
  {
    code: 'MY', numericCode: '458', name: 'Malaisie',
    regime: 'exemption', rates: '0%', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: ['Pas d\'impot sur les gains en capital'],
    keyRules: ['0% gains en capital pour les particuliers', 'Trading frequent peut etre requalifie en revenu (0-30%)', 'Crypto non reconnue comme monnaie legale', 'Regime SC pour les plateformes'],
    notes: 'La Malaisie ne taxe pas les gains en capital crypto mais le trading professionnel peut etre requalifie en revenu imposable.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'LHDN', url: 'https://www.hasil.gov.my/' }],
  },
  {
    code: 'PY', numericCode: '600', name: 'Paraguay',
    regime: 'flat_tax', rates: '8-10%', rateValue: 8,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['Taux IRP 8-10% sur les revenus', 'Electricite bon marche (hydro) pour le minage', 'Cadre legal en construction', 'Projet de loi minage 2024'],
    notes: 'Le Paraguay beneficie d\'une energie bon marche pour le minage. La fiscalite reste faible mais le cadre est en evolution.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SET Paraguay', url: 'https://www.set.gov.py/' }],
  },

  // ─── AMERIQUES ─────────────────────────────────────
  {
    code: 'US', numericCode: '840', name: 'Etats-Unis',
    regime: 'capital_gains', rates: '0-20%', rateValue: 15,
    holdingPeriodRules: [
      { period: '< 1 an', benefit: 'Short-term : impose comme revenu ordinaire (10-37%)' },
      { period: '> 1 an', benefit: 'Long-term : 0%, 15% ou 20% selon revenus' },
    ],
    exemptions: ['0% LTCG si revenu < ~47 000 USD (celibataire)'],
    keyRules: ['Short-term < 1 an = bareme IR (10-37%)', 'Long-term > 1 an = 0/15/20%', 'Reporting IRS via formulaire 8949', 'Wash sale rule pas encore appliquee aux crypto (en discussion)'],
    notes: 'Le regime US est favorable aux holders long terme (0% possible). Le reporting IRS est strict depuis 2024. Les brokers doivent reporter via 1099.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'IRS Notice 2014-21', url: 'https://www.irs.gov/individuals/international-taxpayers/frequently-asked-questions-on-virtual-currency-transactions' }],
  },
  {
    code: 'CA', numericCode: '124', name: 'Canada',
    regime: 'capital_gains', rates: '~12-27%', rateValue: 17,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['50% des gains en capital inclus dans le revenu imposable', 'Bareme federal + provincial', 'Taux effectif ~12-27% selon la province et les revenus', 'CRA considere les crypto comme un bien'],
    notes: 'Le Canada inclut 50% des gains en capital dans le revenu, puis applique le bareme progressif. Le taux effectif varie selon la province.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'CRA', url: 'https://www.canada.ca/en/revenue-agency.html' }],
  },
  {
    code: 'BR', numericCode: '076', name: 'Bresil',
    regime: 'progressive', rates: '15-22,5%', rateValue: 15,
    holdingPeriodRules: [],
    exemptions: ['Ventes < 35 000 BRL/mois exonerees'],
    keyRules: ['15% (< 5M BRL), 17,5% (5-10M), 20% (10-30M), 22,5% (> 30M)', 'Seuil d\'exoneration : 35 000 BRL/mois de ventes', 'Declaration via Receita Federal', 'Obligation de reporter les operations mensuelles'],
    notes: 'Le Bresil a un systeme progressif avec un seuil d\'exoneration mensuel genereux. Le reporting mensuel est obligatoire via le programme GCAP.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Receita Federal', url: 'https://www.gov.br/receitafederal/' }],
  },
  {
    code: 'AR', numericCode: '032', name: 'Argentine',
    regime: 'flat_tax', rates: '15%', rateValue: 15,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['15% sur les gains en capital (cedular)', 'Impot sur les biens personnels', 'Contexte de forte inflation et controle des changes', 'Usage massif de crypto comme refuge'],
    notes: 'L\'Argentine taxe les gains crypto a 15% mais dans un contexte d\'inflation massive et de controles des changes stricts, les crypto servent de refuge financier.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'AFIP', url: 'https://www.afip.gob.ar/' }],
  },
  {
    code: 'MX', numericCode: '484', name: 'Mexique',
    regime: 'progressive', rates: '1,92-35%', rateValue: 20,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['Bareme progressif ISR (1,92-35%)', 'Crypto traitees comme actifs virtuels', 'Loi Fintech de 2018 encadre les plateformes', 'Reporting SAT obligatoire'],
    notes: 'Le Mexique applique le bareme progressif general aux gains crypto. La Loi Fintech encadre les plateformes mais la fiscalite individuelle reste complexe.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SAT Mexico', url: 'https://www.sat.gob.mx/' }],
  },
  {
    code: 'CO', numericCode: '170', name: 'Colombie',
    regime: 'flat_tax', rates: '10%', rateValue: 10,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['10% sur les gains en capital occasionnels', 'Holding > 2 ans = gains occasionnels (10%)', 'Sinon bareme progressif IR (0-39%)', 'DIAN encadre la declaration'],
    notes: 'La Colombie offre un taux reduit de 10% pour les gains en capital occasionnels (detention > 2 ans). Sinon le bareme progressif s\'applique.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'DIAN', url: 'https://www.dian.gov.co/' }],
  },

  // ─── ASIE-PACIFIQUE ────────────────────────────────
  {
    code: 'JP', numericCode: '392', name: 'Japon',
    regime: 'progressive', rates: '15-55%', rateValue: 35,
    holdingPeriodRules: [],
    exemptions: ['Deduction standard de 200 000 JPY/an (~1 300 EUR)'],
    keyRules: ['Revenu divers (miscellaneous income) : bareme progressif 5-45% + taxe locale 10%', 'Taux marginal max 55%', 'Echanges crypto-crypto imposables', 'Pertes non reportables'],
    notes: 'Le Japon a l\'un des regimes les plus severes au monde pour les crypto. Les gains sont traites comme "revenus divers" et non comme gains en capital. Pertes non deductibles.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'NTA Japan', url: 'https://www.nta.go.jp/' }],
  },
  {
    code: 'KR', numericCode: '410', name: 'Coree du Sud',
    regime: 'flat_tax', rates: '20%', rateValue: 20,
    holdingPeriodRules: [],
    exemptions: ['Abattement de 2,5M KRW/an (~1 700 EUR)'],
    keyRules: ['20% sur gains > 2,5M KRW (+ 2% taxe locale = 22%)', 'Entree en vigueur reportee plusieurs fois', 'Declaration annuelle obligatoire', 'Plateformes doivent retenir a la source'],
    notes: 'La Coree a reporte l\'entree en vigueur de la taxe crypto plusieurs fois. Le taux de 20% s\'applique au-dela d\'un abattement annuel.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'NTS Korea', url: 'https://www.nts.go.kr/' }],
  },
  {
    code: 'AU', numericCode: '036', name: 'Australie',
    regime: 'capital_gains', rates: '0-45%', rateValue: 23,
    holdingPeriodRules: [{ period: '> 12 mois', benefit: 'Remise de 50% sur la plus-value (CGT discount)' }],
    exemptions: ['Personal use assets < 10 000 AUD (usage personnel)'],
    keyRules: ['CGT : gains ajoutes au revenu imposable (0-45%)', 'Detention > 12 mois = 50% de remise', 'ATO active dans le suivi des crypto', 'Pertes reportables indefiniment'],
    notes: 'L\'Australie offre un CGT discount de 50% apres 1 an, rendant le taux effectif max ~22,5%. L\'ATO collecte les donnees des exchanges depuis 2019.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'ATO', url: 'https://www.ato.gov.au/individuals-and-families/investments-and-assets/crypto-asset-investments' }],
  },
  {
    code: 'NZ', numericCode: '554', name: 'Nouvelle-Zelande',
    regime: 'progressive', rates: '10,5-39%', rateValue: 25,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['Gains crypto traites comme revenu (pas CGT)', 'Bareme IR progressif (10,5-39%)', 'IRD considere les crypto comme une "propriete"', 'Intention d\'achat determinante pour l\'imposition'],
    notes: 'La Nouvelle-Zelande n\'a pas de CGT mais les gains crypto sont traites comme revenu si l\'intention de revente existait a l\'achat. Le cadre est complexe.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'IRD NZ', url: 'https://www.ird.govt.nz/' }],
  },
  {
    code: 'IN', numericCode: '356', name: 'Inde',
    regime: 'flat_tax', rates: '30%', rateValue: 30,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['30% flat tax sur les gains (VDA = Virtual Digital Assets)', '1% TDS (Tax Deducted at Source) sur chaque transaction', 'Aucune deduction de pertes possible', 'Pertes non reportables, pas de deduction de frais'],
    notes: 'L\'Inde impose un regime tres strict depuis 2022 : 30% flat + 1% TDS. Impossible de deduire les pertes ou les frais. L\'un des regimes les plus punitifs au monde.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Income Tax India', url: 'https://incometaxindia.gov.in/' }],
  },
  {
    code: 'TH', numericCode: '764', name: 'Thailande',
    regime: 'flat_tax', rates: '15%', rateValue: 15,
    holdingPeriodRules: [],
    exemptions: ['Exoneration temporaire des gains crypto sur exchanges autorises (en discussion)'],
    keyRules: ['15% withholding tax sur les gains', 'Possibilite d\'integration au bareme progressif (0-35%)', 'SEC Thailand regule les plateformes', 'TVA exoneree pour les crypto (temporaire)'],
    notes: 'La Thailande a clarifie son regime avec un taux de 15%. Des exemptions temporaires ont ete discutees pour stimuler l\'adoption.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Revenue Department Thailand', url: 'https://www.rd.go.th/' }],
  },
  {
    code: 'ID', numericCode: '360', name: 'Indonesie',
    regime: 'flat_tax', rates: '0,1%', rateValue: 0.1,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['0,1% d\'impot sur chaque transaction crypto', '0,11% de TVA sur les transactions', 'Regime base sur la transaction, pas sur le gain', 'Bappebti regule le marche crypto'],
    notes: 'L\'Indonesie a un systeme unique : taxe de 0,1% sur chaque transaction (pas sur le gain). Simple mais s\'accumule pour les traders actifs.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'Bappebti', url: 'https://bappebti.go.id/' }],
  },
  {
    code: 'PH', numericCode: '608', name: 'Philippines',
    regime: 'flat_tax', rates: '15%', rateValue: 15,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['15% capital gains tax', 'BIR encadre la declaration', 'BSP regule les exchanges', 'Cadre en evolution'],
    notes: 'Les Philippines appliquent un CGT de 15% sur les gains crypto. Le cadre regulatoire continue d\'evoluer via la BSP.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'BIR', url: 'https://www.bir.gov.ph/' }],
  },

  // ─── AFRIQUE / MOYEN-ORIENT ───────────────────────
  {
    code: 'IL', numericCode: '376', name: 'Israel',
    regime: 'capital_gains', rates: '25%', rateValue: 25,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['25% CGT (ou 30% pour les actionnaires significatifs)', 'ITA considere les crypto comme un actif', 'Declaration obligatoire via formulaire 1399', 'Pas de distinction court/long terme'],
    notes: 'Israel applique un CGT de 25% sans distinction de duree de detention. Le pays est un hub technologique important avec un ecosysteme crypto actif.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'ITA', url: 'https://www.gov.il/en/departments/israel-tax-authority' }],
  },
  {
    code: 'ZA', numericCode: '710', name: 'Afrique du Sud',
    regime: 'capital_gains', rates: '18%', rateValue: 18,
    holdingPeriodRules: [],
    exemptions: ['Exclusion annuelle de 40 000 ZAR (~2 000 EUR)'],
    keyRules: ['Taux d\'inclusion de 40% (particuliers)', 'Taux marginal max 45%, soit CGT effectif ~18%', 'Exclusion annuelle de 40 000 ZAR', 'SARS a commence a traquer les traders crypto'],
    notes: 'L\'Afrique du Sud inclut 40% des gains en capital dans le revenu imposable. Le taux effectif max est d\'environ 18%. SARS renforce le suivi depuis 2023.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SARS', url: 'https://www.sars.gov.za/' }],
  },
  {
    code: 'NG', numericCode: '566', name: 'Nigeria',
    regime: 'unclear', rates: '10%', rateValue: 10,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['CGT de 10% (en theorie)', 'Cadre regulatoire flou et changeant', 'CBN a interdit aux banques les transactions crypto (2021, partiellement leve)', 'SEC Nigeria travaille sur un cadre', 'Adoption massive malgre les restrictions'],
    notes: 'Le Nigeria a l\'un des taux d\'adoption crypto les plus eleves au monde malgre un cadre flou. La banque centrale a assoupli sa position mais la reglementation reste incertaine.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'SEC Nigeria', url: 'https://sec.gov.ng/' }],
  },
  {
    code: 'MA', numericCode: '504', name: 'Maroc',
    regime: 'unclear', rates: 'N/A', rateValue: 0,
    holdingPeriodRules: [],
    exemptions: [],
    keyRules: ['Crypto officiellement interdites (circulaire BAM 2017)', 'Projet de loi en preparation depuis 2023', 'Adoption significative malgre l\'interdiction', 'Cadre fiscal inexistant'],
    notes: 'Le Maroc interdit officiellement les cryptomonnaies mais l\'adoption est forte. Un projet de loi est en cours pour reguler et potentiellement taxer les crypto.',
    lastUpdated: '2025-01-01',
    sources: [{ label: 'BAM', url: 'https://www.bkam.ma/' }],
  },
];

// ─── HELPERS ─────────────────────────────────────────

const byCode = new Map(TAX_DATA.map(c => [c.code, c]));
const byNumeric = new Map(TAX_DATA.map(c => [c.numericCode, c]));

export function getCountryByCode(code: string): CountryTaxInfo | undefined {
  return byCode.get(code);
}

export function getCountryByNumericCode(numCode: string): CountryTaxInfo | undefined {
  return byNumeric.get(numCode);
}

export function getRegimeColor(regime: TaxRegime): string {
  return REGIME_COLORS[regime];
}

export function searchCountries(query: string): CountryTaxInfo[] {
  const q = query.toLowerCase().trim();
  if (!q) return TAX_DATA;
  return TAX_DATA.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.code.toLowerCase().includes(q)
  );
}

export function filterByRegime(regime: TaxRegime | 'all'): CountryTaxInfo[] {
  if (regime === 'all') return TAX_DATA;
  return TAX_DATA.filter(c => c.regime === regime);
}

export const DEFAULT_COMPARISON = ['FR', 'PT', 'CH', 'AE'];
